#!/bin/bash
# See https://github.com/adriancooney/Taskfile for examples

# Sane error handling
set -o errexit -o pipefail -o nounset

function already_open {
	opened="$(poetry run python list-fftabs.py)"
	# implicit return the exit status of grep
	grep -q "$1$" <<<"$opened"
}

### FUNCTIONS GO HERE
function default {
	: "By default, run test suite"
	task:test
}

function task:test {
	: "Run unit test suite"
	poetry run nose2 --verbose
}

function task:docs {
	: "Build and open docs"
	target="docs/_build/html/index.html"
	poetry run make "$target"
	if ! already_open "$target" ; then
		firefox "$target"
	fi
}

function task:deploy_docs {
	: "Put the HTML documentation onto my pi"
	target="docs/_build/html/index.html"
	docs_theme=nature poetry run make "$target"
	tar c -z -C docs/_build/html . | ssh -i ~/.ssh/server_id server@nthurmes.duckdns.org 'mkdir -p /var/www/docs/dndice && cat | tar x -z -C /var/www/docs/dndice'
}

function task:build {
	: "Build wheel from the sources"
	poetry run make "dist/dndice-$(poetry version --short)-py3-none-any.whl"
}

function task:publish {
	: "Publish to PyPi"
	task:build
	poetry publish
}

function task:coverage {
	: "Compile and open unit test coverage statistics"
	target="htmlcov/index.html"
	poetry run make "$target"
	if ! already_open "$target" ; then
		firefox "$target"
	fi
}

function task:test_compatibility {
	: "Run the test suite against multiple versions of python, including one of pypy"
	for v in "python:3.5-alpine" "python:3.8-alpine" "jamiehewland/alpine-pypy:3.6-alpine3.11" ; do
		docker build -t dndice_compat --build-arg image="$v" . && docker run --rm --name rolling_test dndice_compat
	done
}

function task:clean {
	: "Clean up generated files"
	git clean -xdf -e '/venv' -e '/.idea'
}

function task:coveralls {
	: "Upload coverage data to coveralls to use badge"
	if [[ ! $(git symbolic-ref HEAD) = refs/heads/master ]] || [[ -z "$(git status --porcelain)" ]] ; then
		echo "Must be on the main branch and have a clean working tree for results to be meaningful." >&2
		return 1
	fi
	task:coverage
	poetry run coveralls
}

### /FUNCTIONS GO HERE

# Auto-generate list of tasks
function task:help {
	: "Auto-generate a list of tasks"
	compgen -A function | grep '^task:' | cut -d':' -f 2- | while read -r name ; do
		paste <(printf '%s' "$name") <(type "task:$name" | sed -nE 's/[[:space:]]+: "(.*)";$/\1/p')
	done
}

if [[ $# -eq 0 ]] ; then
	default
else
	cmd="$1"
	shift
	"task:$cmd" "$@"
fi
